micronaut:
  application:
    name: stockinfo
  server:
    port: -1
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

consul:
  client:
    registration:
      enabled: true
    defaultZone: ${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}

r2dbc:
  datasources:
    default:
      schema-generate: CREATE_DROP
      dialect: H2
      url: r2dbc:h2:mem:///stocksdb;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: ''
      options:
        DB_CLOSE_DELAY: -1
        protocol: mem
