micronaut:
  application:
    name: stockinfo
  server:
    port: -1

consul:
  client:
    registration:
      enabled: true
    defaultZone: ${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}

datasources:
  default:
    url: jdbc:h2:mem:stocksdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generated: CREATE
    dialect: H2

jpa:
  default:
    entity-scan:
      packages: 'com.agiledeveloper'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
          show_sql: true
